title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: 
- jekyll-remote-theme # add this line to the plugins list if you already have one
- [jekyll-paginate]
paginate: 5
remote_theme: pages-themes/cayman@v0.2.0



navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com
  linkedin: brianmaierjr

google_analytics: false
google_adsense: true
disqus:
    shortname: brianmaierjr
